language: objective-c
osx_image: xcode7
xcode_workspace: MCIconAlertControllerExample/MCIconAlertControllerExample.xcworkspace
xcode_scheme: MCIconAlertControllerExample
podfile: MCIconAlertControllerExample/Podfile
notifications:
    email: false
#script: script/cibuild
script:
- xctool
    -workspace MCIconAlertControllerExample/MCIconAlertControllerExample.xcworkspace
    -scheme MCIconAlertControllerExample
    -sdk iphonesimulator
    build
    test
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
