language: objective-c
before_install:
    - brew update
    - brew install xctool
osx_image: xcode7.3
podfile: MCIconAlertControllerExample/Podfile
notifications:
    email: false
#script: script/cibuild
script:
    xctool
    -workspace MCIconAlertControllerExample/MCIconAlertControllerExample.xcworkspace
    -scheme MCIconAlertControllerExample
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
    test
