language: objective-c
osx_image: xcode7.3
podfile: MCIconAlertControllerExample/Podfile
notifications:
    email: false
#script: script/cibuild
script:
    xctool \
    -workspace MCIconAlertControllerExample/MCIconAlertControllerExample.xcworkspace \
    -scheme MCIconAlertControllerExampleTests \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus' \
    build \
    test
