target :'MCIconAlertController' do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '6.0'
    
    pod 'Masonry', '~> 1.0'
    
    target "MCIconAlertControllerTests" do
        inherit! :search_paths
        #pod 'OCMock', '~> 2.0.1'
    end
end
